# Generated by Django 5.0.2 on 2025-03-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0024_rename_user_testimonial_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='addictiondetails',
            name='other_relationship_specification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
