# Generated by Django 5.0.2 on 2025-03-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprehab', '0025_addictiondetails_other_relationship_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='addictiondetails',
            name='guider_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
